CREATE DATABASE library_management;
USE library_management;

CREATE TABLE SYSTEM_USER (
    User_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE STAFF (
    Staff_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Hire_Date DATE NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES SYSTEM_USER(User_ID)
);

CREATE TABLE MEMBER (
    Member_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Phone VARCHAR(11) NOT NULL,
    Address VARCHAR(200) NOT NULL,
    Join_Date DATE NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES SYSTEM_USER(User_ID)
);

CREATE TABLE AUTHORS (
    Author_ID INT AUTO_INCREMENT PRIMARY KEY,
    Author_Name VARCHAR(100) NOT NULL,
    Nationality VARCHAR(50)
);

CREATE TABLE CATEGORIES (
    Category_ID INT AUTO_INCREMENT PRIMARY KEY,
    Category_Name VARCHAR(100) NOT NULL
);

CREATE TABLE PUBLISHERS (
    Publisher_ID INT AUTO_INCREMENT PRIMARY KEY,
    Publisher_Name VARCHAR(100) NOT NULL,
    Country VARCHAR(50)
);

CREATE TABLE BOOKS (
    Book_ID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Author_ID INT NOT NULL,
    Category_ID INT NOT NULL,
    Publisher_ID INT NOT NULL,
    ISBN VARCHAR(20) NOT NULL UNIQUE,
    Publish_Year INT,
    Copies_Total INT NOT NULL,
    Copies_Available INT NOT NULL,
    Shelf_Location VARCHAR(50) NOT NULL,
    FOREIGN KEY (Author_ID) REFERENCES AUTHORS(Author_ID),
    FOREIGN KEY (Category_ID) REFERENCES CATEGORIES(Category_ID),
    FOREIGN KEY (Publisher_ID) REFERENCES PUBLISHERS(Publisher_ID)
);

CREATE TABLE BORROWING (
    Borrow_ID INT AUTO_INCREMENT PRIMARY KEY,
    Member_ID INT NOT NULL,
    Book_ID INT NOT NULL,
    Staff_ID INT NOT NULL,
    Borrow_Date DATE NOT NULL,
    Due_Date DATE NOT NULL,
    Return_Date DATE,
    Status VARCHAR(20) NOT NULL,
    FOREIGN KEY (Member_ID) REFERENCES MEMBER(Member_ID),
    FOREIGN KEY (Book_ID) REFERENCES BOOKS(Book_ID),
    FOREIGN KEY (Staff_ID) REFERENCES STAFF(Staff_ID)
);

CREATE TABLE FINE (
    Fine_ID INT AUTO_INCREMENT PRIMARY KEY,
    Borrow_ID INT NOT NULL UNIQUE,
    Amount DECIMAL(10,2) NOT NULL,
    Paid VARCHAR(3) NOT NULL,
    FOREIGN KEY (Borrow_ID) REFERENCES BORROWING(Borrow_ID)
);

